[package]
org = "ballerinax"
name = "kafka"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "io"
version = "@stdlib.io.version@"

[[dependency]]
org = "ballerina"
name = "config"
version = "@stdlib.config.version@"

[[dependency]]
org = "ballerina"
name = "time"
version = "@stdlib.time.version@"

[[dependency]]
org = "ballerina"
name = "runtime"
version = "@stdlib.runtime.version@"

[[dependency]]
org = "ballerina"
name = "file"
version = "@stdlib.file.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[dependency]]
org = "ballerina"
name = "system"
version = "@stdlib.system.version@"

[[dependency]]
org = "ballerina"
name = "stringutils"
version = "@stdlib.stringutils.version@"

[[platform.java11.dependency]]
path = "../kafka-native/build/libs/kafka-native-@project.version@.jar"
groupId = "org.ballerinalang.messaging.kafka"
artifactId = "kafka"
version = "@project.version@"


[[platform.java11.dependency]]
path = "./lib/kafka-clients-@kafka.version@.jar"
groupId = "org.apache.kafka"
artifactId = "kafka-clients"
version = "@kafka.version@"


[[platform.java11.dependency]]
path = "./lib/kafka_2.12-@kafka.version@.jar"
groupId = "org.apache.kafka"
artifactId = "kafka_2.12"
version = "@kafka.version@"


[[platform.java11.dependency]]
path = "./lib/avro-1.9.2.jar"
groupId = "org.apache.avro"
scope = "compile"
artifactId = "avro"
version = "1.9.2"
